version: '2.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    volumes:
#      - /docker_data/zookeeper-2181/conf:/conf
      - /docker_data/zookeeper-2181/logs:/logs
      - /docker_data/zookeeper-2181/data:/data
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    volumes:
#      - /docker_data/zookeeper-2182/conf:/conf
      - /docker_data/zookeeper-2182/logs:/logs
      - /docker_data/zookeeper-2182/data:/data
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    volumes:
#      - /docker_data/zookeeper-2183/conf:/conf
      - /docker_data/zookeeper-2183/logs:/logs
      - /docker_data/zookeeper-2183/data:/data
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
